// Code generated by agent. DO NOT EDIT.

package agent

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/dknr/bantam/session"
)

func TestBuildMessages(t *testing.T) {
	// Create a temporary directory for the session SQLite file
	tmpDir, err := os.MkdirTemp("", "bantam_agent_test")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create a session manager and session
	sessMgr := session.NewManager(filepath.Join(tmpDir, "sessions.db"))

	// Get or create a session
	sess := sessMgr.GetOrCreate("test:test")
	if sess == nil {
		t.Fatalf("GetOrCreate returned nil session")
	}

	// Add some messages to the session
	sess.AddMessage("system", "You are a helpful assistant.")
	sess.AddMessage("user", "Hello, world!")
	sess.AddMessage("assistant", "Hi there!")

	// Debug: check history right after adding
	history := sess.History()
	t.Logf("After adding messages, history length: %d", len(history))
	for i, msg := range history {
		t.Logf("  [%d] role=%s, content=%s", i, msg.Role, msg.Content)
	}

	// Create an agent with nil dependencies (we only need buildMessages)
	a := &Agent{
		provider:     nil,
		toolRegistry: nil,
		sessionMgr:   sessMgr,
		InputChan:    make(chan string, 10),
		OutputChan:   make(chan OutputMessage, 10),
		channel:      "test",
		chatID:       "test",
	}

	// Call buildMessages
	messages := a.buildMessages(sess)
	t.Logf("buildMessages returned %d messages", len(messages))

	// Cleanup
	sess.Close()

	// Assertions
	if len(messages) != 3 {
		t.Fatalf("Expected 3 messages, got %d", len(messages))
	}

	// Check system message
	if role, ok := messages[0]["role"]; !ok || role != "system" {
		t.Fatalf("Expected role system, got %v", messages[0]["role"])
	}
	if content, ok := messages[0]["content"]; !ok || content != "You are a helpful assistant." {
		t.Fatalf("Expected content 'You are a helpful assistant.', got %v", messages[0]["content"])
	}

	// Check user message
	if role, ok := messages[1]["role"]; !ok || role != "user" {
		t.Fatalf("Expected role user, got %v", messages[1]["role"])
	}
	if content, ok := messages[1]["content"]; !ok || content != "Hello, world!" {
		t.Fatalf("Expected content 'Hello, world!', got %v", messages[1]["content"])
	}

	// Check assistant message
	if role, ok := messages[2]["role"]; !ok || role != "assistant" {
		t.Fatalf("Expected role assistant, got %v", messages[2]["role"])
	}
	if content, ok := messages[2]["content"]; !ok || content != "Hi there!" {
		t.Fatalf("Expected content 'Hi there!', got %v", messages[2]["content"])
	}
}

func TestBuildMessagesWithToolCalls(t *testing.T) {
	t.Logf("Starting TestBuildMessagesWithToolCalls")
	// Create a temporary directory for the session SQLite file
	tmpDir, err := os.MkdirTemp("", "bantam_agent_test2")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create a session manager and session
	sessMgr := session.NewManager(filepath.Join(tmpDir, "sessions.db"))

	// Get or create a session
	sess := sessMgr.GetOrCreate("test:test")
	if sess == nil {
		t.Fatalf("GetOrCreate returned nil session")
	}

	// Add a system message
	sess.AddMessage("system", "You are a helpful assistant.")

	// Add a user message
	sess.AddMessage("user", "What's the weather?")

	// Add an assistant message with tool calls (as JSON)
	assistantJSON := `{"content": "Let me check the weather for you.", "tool_calls": [{"ID": "call_123", "Name": "weather", "Arguments": {"location": "New York"}}]}`
	sess.AddMessage("assistant", assistantJSON)

	// Debug: check history right after adding
	history := sess.History()
	t.Logf("After adding messages, history length: %d", len(history))
	for i, msg := range history {
		t.Logf("  [%d] role=%s, content=%s", i, msg.Role, msg.Content)
		if msg.Role == "assistant" {
			t.Logf("    Assistant content: %s", msg.Content)
			var raw map[string]interface{}
			if err := json.Unmarshal([]byte(msg.Content), &raw); err != nil {
				t.Logf("    Failed to unmarshal: %v", err)
			} else {
				t.Logf("    Parsed: %+v", raw)
				if tc, ok := raw["tool_calls"]; ok {
					t.Logf("    Tool calls raw: %v", tc)
				}
			}
		}
	}

	// Create an agent with nil dependencies (we only need buildMessages)
	a := &Agent{
		provider:     nil,
		toolRegistry: nil,
		sessionMgr:   sessMgr,
		InputChan:    make(chan string, 10),
		OutputChan:   make(chan OutputMessage, 10),
		channel:      "test",
		chatID:       "test",
	}

	// Call buildMessages
	messages := a.buildMessages(sess)
	t.Logf("buildMessages returned %d messages", len(messages))
	if len(messages) >= 3 {
		assistantMsg := messages[2]
		if role, ok := assistantMsg["role"]; ok && role == "assistant" {
			t.Logf("Assistant message from buildMessages: role=%s, content=%s", role, assistantMsg["content"])
			if tc, ok := assistantMsg["tool_calls"]; ok {
				t.Logf("Tool calls in buildMessages result: %v", tc)
			}
		}
	}

	// Cleanup
	sess.Close()

	// Assertions
	if len(messages) != 3 {
		t.Fatalf("Expected 3 messages, got %d", len(messages))
	}

	// Check system message
	if role, ok := messages[0]["role"]; !ok || role != "system" {
		t.Fatalf("Expected role system, got %v", messages[0]["role"])
	}
	if content, ok := messages[0]["content"]; !ok || content != "You are a helpful assistant." {
		t.Fatalf("Expected content 'You are a helpful assistant.', got %v", messages[0]["content"])
	}

	// Check user message
	if role, ok := messages[1]["role"]; !ok || role != "user" {
		t.Fatalf("Expected role user, got %v", messages[1]["role"])
	}
	if content, ok := messages[1]["content"]; !ok || content != "What's the weather?" {
		t.Fatalf("Expected content 'What's the weather?', got %v", messages[1]["content"])
	}

	// Check assistant message (should have been converted)
	if role, ok := messages[2]["role"]; !ok || role != "assistant" {
		t.Fatalf("Expected role assistant, got %v", messages[2]["role"])
	}
	if content, ok := messages[2]["content"]; !ok || content != "Let me check the weather for you." {
		t.Fatalf("Expected content 'Let me check the weather for you.', got %v", messages[2]["content"])
	}
	// Check that tool_calls is present and correctly formatted
	toolCalls := messages[2]["tool_calls"]
	if toolCalls == nil {
		t.Fatalf("Expected tool_calls to be present")
	}
	tcSlice, ok := toolCalls.([]map[string]interface{})
	if !ok {
		t.Fatalf("Expected tool_calls to be []map[string]interface{}, got %T", toolCalls)
	}
	if len(tcSlice) != 1 {
		t.Fatalf("Expected 1 tool call, got %d", len(tcSlice))
	}
	tcMap := tcSlice[0]
	if id, ok := tcMap["id"]; !ok || id != "call_123" {
		t.Fatalf("Expected id 'call_123', got %v", tcMap["id"])
	}
	// Check the type field
	if typ, ok := tcMap["type"]; !ok || typ != "function" {
		t.Fatalf("Expected type 'function', got %v", tcMap["type"])
	}
	// The function field should be a map with name and arguments
	functionMap := tcMap["function"].(map[string]interface{})
	if functionMap == nil {
		t.Fatalf("Expected function map")
	}
	if fname, ok := functionMap["name"]; !ok || fname != "weather" {
		t.Fatalf("Expected function name 'weather', got %v", functionMap["name"])
	}
	if fargs, ok := functionMap["arguments"]; !ok || fargs != "{\"location\":\"New York\"}" {
		t.Fatalf("Expected function arguments '{\"location\":\"New York\"}', got %v", functionMap["arguments"])
	}
}